import assert from 'node:assert';
import { describe, it } from 'node:test';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { JSDOM } from 'jsdom';
import { createRoot } from 'react-dom/client';
import { flushSync } from 'react-dom';

import SummaryTab from '../src/components/SummaryTab';
import VerdictCard from '../src/components/VerdictCard';
import ExpandableCostRow from '../src/components/ExpandableCostRow';
import { CommuteInput } from '../src/types';
import { calculateCommuteArbitrage } from '../src/lib/calculator';
import { CommuteVerdict } from '../src/types/commute';

// Section 5 Benchmark Fixture: Mt Roskill to Parnell, Diesel, 3 days/wk, $4.00 parking
const fixtureInput: CommuteInput = {
  originSuburbId: 'mt-roskill',
  destinationSuburbId: 'parnell',
  daysPerWeek: 3,
  vehicleType: 'diesel',
  powertrain: 'DIESEL',
  parkingDailyRate: 4.0,
  parkingDaysPerWeek: 3,
  concession: 'adult',
  carpoolPassengers: 1,
  includeMaintenanceWear: true,
  distanceWearWeekly: 3.0,
};

describe('STORY-4: Summary Tab & Layered Disclosure UI', () => {
  const arbitrage = calculateCommuteArbitrage(fixtureInput);

  describe('Task 1: VerdictCard.tsx', () => {
    it('renders exact headline and supporting copy generated by the verdict engine', () => {
      const verdict: CommuteVerdict = {
        state: 'about_the_same',
        headline: 'Pretty much a wash',
        support:
          "You'd stop paying $30 a week for the car and pay $29 in fares. The bus takes 56 minutes longer each day.",
        band: 3,
        differenceWeekly: 0.18,
        savingsWeekly: 0,
        savingsAnnual: 0,
        isWash: true,
        isTransitCheaper: false,
        isDrivingCheaper: false,
        timeDeltaMinutesDaily: 56,
      };

      const html = renderToStaticMarkup(React.createElement(VerdictCard, { verdict }));

      assert.ok(html.includes('Pretty much a wash'), 'Must display exact headline');
      assert.ok(
        html.includes(
          "You&#x27;d stop paying $30 a week for the car and pay $29 in fares. The bus takes 56 minutes longer each day."
        ) ||
          html.includes(
            "You'd stop paying $30 a week for the car and pay $29 in fares. The bus takes 56 minutes longer each day."
          ),
        'Must display exact supporting sentence'
      );
      assert.ok(html.includes('Cost Wash'), 'Must display wash badge');
    });

    it('renders transit cheaper copy and savings badge correctly', () => {
      const verdict: CommuteVerdict = {
        state: 'transit_cheaper',
        headline: 'The bus would save you about $25 a week',
        support: "That's roughly $1,300 a year, and the bus takes 15 minutes longer each day.",
        band: 5,
        differenceWeekly: 25.0,
        savingsWeekly: 25.0,
        savingsAnnual: 1300,
        isWash: false,
        isTransitCheaper: true,
        isDrivingCheaper: false,
        timeDeltaMinutesDaily: 15,
      };

      const html = renderToStaticMarkup(React.createElement(VerdictCard, { verdict }));
      assert.ok(html.includes('The bus would save you about $25 a week'), 'Must display transit cheaper headline');
      assert.ok(html.includes('Transit Saves Money'), 'Must display transit savings badge');
    });

    it('renders driving cheaper copy correctly', () => {
      const verdict: CommuteVerdict = {
        state: 'driving_cheaper',
        headline: 'Driving is cheaper by about $15 a week',
        support: 'And it saves you 25 minutes a day.',
        band: 3.5,
        differenceWeekly: 15.0,
        savingsWeekly: 0,
        savingsAnnual: 0,
        isWash: false,
        isTransitCheaper: false,
        isDrivingCheaper: true,
        timeDeltaMinutesDaily: 25,
      };

      const html = renderToStaticMarkup(React.createElement(VerdictCard, { verdict }));
      assert.ok(html.includes('Driving is cheaper by about $15 a week'), 'Must display driving cheaper headline');
      assert.ok(html.includes('Driving Is Cheaper'), 'Must display driving cheaper badge');
    });
  });

  describe('Task 3: ExpandableCostRow.tsx', () => {
    it('renders total and title cleanly, expanding and collapsing when clicked', () => {
      const dom = new JSDOM('<!DOCTYPE html><html><body><div id="root"></div></body></html>');
      // @ts-ignore
      global.window = dom.window;
      // @ts-ignore
      global.document = dom.window.document;

      const container = dom.window.document.getElementById('root')!;
      const root = createRoot(container);

      flushSync(() => {
        root.render(
          React.createElement(ExpandableCostRow, {
            id: 'test-row',
            title: "What you'd stop paying",
            total: 29.58,
            items: [
              { label: 'Fuel / Energy', amount: 10.11 },
              { label: 'Parking', amount: 12.0 },
              { label: 'Other servicing', amount: 'Included', isIncluded: true },
            ],
            defaultExpanded: false,
          })
        );
      });

      const button = container.querySelector('#cost-header-test-row') as HTMLButtonElement;
      assert.ok(button, 'Cost row button exists');
      assert.strictEqual(button.getAttribute('aria-expanded'), 'false', 'Initial aria-expanded is false');
      assert.strictEqual(container.querySelector('#cost-content-test-row'), null, 'Sub-items initially collapsed');

      // Click to expand
      flushSync(() => {
        button.click();
      });

      assert.strictEqual(button.getAttribute('aria-expanded'), 'true', 'aria-expanded toggled to true');
      const content = container.querySelector('#cost-content-test-row');
      assert.ok(content, 'Sub-items container is now rendered in DOM');
      assert.ok(content.textContent?.includes('Fuel / Energy'), 'Renders Fuel line item');
      assert.ok(content.textContent?.includes('$10.11'), 'Renders Fuel amount');
      assert.ok(content.textContent?.includes('Included'), 'Renders Included badge for bundled servicing');

      // Click to collapse
      flushSync(() => {
        button.click();
      });

      assert.strictEqual(button.getAttribute('aria-expanded'), 'false', 'aria-expanded toggled back to false');
      assert.strictEqual(container.querySelector('#cost-content-test-row'), null, 'Sub-items collapsed again');

      flushSync(() => {
        root.unmount();
      });
    });

    it('explicitly renders "Included" for zero-cost or bundled servicing instead of $0.00', () => {
      const html = renderToStaticMarkup(
        React.createElement(ExpandableCostRow, {
          id: 'still-pay',
          title: "What you'd still pay",
          total: 18.12,
          defaultExpanded: true,
          items: [
            { label: 'Insurance', amount: 13.56 },
            { label: 'Other servicing', amount: 'Included', isIncluded: true },
          ],
        })
      );

      assert.ok(html.includes('Included'), 'Must render "Included" text badge');
      assert.ok(!html.includes('$0.00'), 'Must never render $0.00 for bundled servicing');
    });
  });

  describe('Task 2, 4, 5: SummaryTab Component Integration', () => {
    it('renders the Trip line with origin, destination, days, and Change button (Task 2)', () => {
      const html = renderToStaticMarkup(
        React.createElement(SummaryTab, {
          commuteInput: fixtureInput,
          setCommuteInput: () => {},
          arbitrage,
        })
      );

      assert.ok(
        html.includes('Mount Roskill to Parnell, 3 days a week') ||
          html.includes('Mt Roskill to Parnell, 3 days a week'),
        'Trip line must display formatted route'
      );
      assert.ok(html.includes('Change'), 'Trip line must contain Change button');
    });

    it('clicking Change next to trip line triggers onEditCommute callback and eliminates legacy inline drawer', () => {
      const dom = new JSDOM('<!DOCTYPE html><html><body><div id="root"></div></body></html>');
      // @ts-ignore
      global.window = dom.window;
      // @ts-ignore
      global.document = dom.window.document;

      const container = dom.window.document.getElementById('root')!;
      const root = createRoot(container);

      let editStep: number | undefined;
      flushSync(() => {
        root.render(
          React.createElement(SummaryTab, {
            commuteInput: fixtureInput,
            setCommuteInput: () => {},
            arbitrage,
            onEditCommute: (step) => {
              editStep = step;
            },
          })
        );
      });

      const changeBtn = container.querySelector('[data-testid="summary-change-route-btn"]') as HTMLButtonElement;
      assert.ok(changeBtn, 'Change route button must exist');

      flushSync(() => {
        changeBtn.click();
      });

      assert.strictEqual(editStep, 1, 'Clicking Change button must invoke onEditCommute with step 1');

      // Verify legacy inline drawer elements do NOT exist in the DOM
      assert.strictEqual(container.querySelector('#origin-select'), null, 'Legacy origin-select dropdown must be eliminated');
      assert.strictEqual(container.querySelector('#dest-select'), null, 'Legacy dest-select dropdown must be eliminated');
      assert.strictEqual(container.textContent?.includes('EDIT COMMUTE ROUTE & FREQUENCY'), false, 'Legacy drawer header must be eliminated');

      flushSync(() => {
        root.unmount();
      });
    });

    it('renders both expandable cost rows with exact Story 1 model totals (Task 3)', () => {
      const html = renderToStaticMarkup(
        React.createElement(SummaryTab, {
          commuteInput: fixtureInput,
          setCommuteInput: () => {},
          arbitrage,
        })
      );

      // Section 5 fixture check: stops=$29.58, stays=$18.12
      assert.ok(html.includes("What you&#x27;d stop paying") || html.includes("What you'd stop paying"));
      assert.ok(html.includes('$29.58'), 'Must render exact stops total $29.58');

      assert.ok(html.includes("What you&#x27;d still pay") || html.includes("What you'd still pay"));
      assert.ok(html.includes('$18.12'), 'Must render exact stays total $18.12');
    });

    it('renders explicit footnote matching exact requirement copy (Task 4)', () => {
      const html = renderToStaticMarkup(
        React.createElement(SummaryTab, {
          commuteInput: fixtureInput,
          setCommuteInput: () => {},
          arbitrage,
        })
      );

      // Requirement: "Per week. Total cost of the car for this commute: $<fullCost>. We assumed $<wearAssumption> of servicing and wear depends on how much you drive. Change"
      assert.ok(
        html.includes(
          'Per week. Total cost of the car for this commute: $47.70. We assumed $3.00 of servicing and wear depends on how much you drive.'
        ),
        'Footnote must contain exact fullCost ($47.70) and wearAssumption ($3.00)'
      );
      assert.ok(html.includes('Change'), 'Footnote must include interactive Change action');
    });

    it('renders By car and By bus daily commute time cards (Task 5)', () => {
      const html = renderToStaticMarkup(
        React.createElement(SummaryTab, {
          commuteInput: fixtureInput,
          setCommuteInput: () => {},
          arbitrage,
        })
      );

      // Driving time: 18m each way -> 36 min a day
      assert.ok(html.includes('By car, 36 min a day'), 'Must display "By car, 36 min a day"');
      assert.ok(html.includes('18m each way'), 'Must display "18m each way"');

      // Transit time: 46m each way -> 92 min a day
      assert.ok(html.includes('By bus, 92 min a day'), 'Must display "By bus, 92 min a day"');
      assert.ok(html.includes('46m each way'), 'Must display "46m each way"');
    });
  });

  describe('Task 6: WCAG AA Color Contrast Verification', () => {
    // Relative luminance calculation according to WCAG 2.1 specifications
    function getLuminance(r: number, g: number, b: number): number {
      const a = [r, g, b].map((v) => {
        v /= 255;
        return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
      });
      return a[0] * 0.2126 + a[1] * 0.7152 + a[2] * 0.0722;
    }

    function getContrastRatio(rgb1: [number, number, number], rgb2: [number, number, number]): number {
      const lum1 = getLuminance(...rgb1);
      const lum2 = getLuminance(...rgb2);
      const brightest = Math.max(lum1, lum2);
      const darkest = Math.min(lum1, lum2);
      return (brightest + 0.05) / (darkest + 0.05);
    }

    const darkBg: [number, number, number] = [9, 13, 22]; // #090d16
    const cardBg: [number, number, number] = [15, 23, 42]; // #0f172a (slate-900)

    it('verifies secondary text color text-slate-300 passes WCAG AA 4.5:1 on dark background', () => {
      const slate300: [number, number, number] = [203, 213, 225]; // #cbd5e1
      const ratioOnDark = getContrastRatio(slate300, darkBg);
      const ratioOnCard = getContrastRatio(slate300, cardBg);

      assert.ok(ratioOnDark >= 4.5, `slate-300 contrast on dark bg (${ratioOnDark.toFixed(2)}) must exceed 4.5:1`);
      assert.ok(ratioOnCard >= 4.5, `slate-300 contrast on card bg (${ratioOnCard.toFixed(2)}) must exceed 4.5:1`);
    });

    it('verifies primary text color text-white and text-slate-100 pass WCAG AAA (>= 7:1)', () => {
      const white: [number, number, number] = [255, 255, 255];
      const ratio = getContrastRatio(white, darkBg);
      assert.ok(ratio >= 7.0, `White contrast (${ratio.toFixed(2)}) must exceed 7:1`);
    });

    it('verifies emerald-400 accent text color passes WCAG AA for normal text on dark backgrounds', () => {
      const emerald400: [number, number, number] = [52, 211, 153]; // #34d399
      const ratio = getContrastRatio(emerald400, darkBg);
      assert.ok(ratio >= 4.5, `emerald-400 contrast (${ratio.toFixed(2)}) must exceed 4.5:1`);
    });
  });

  describe('BUG-15: Multimodal Primary Mode Hierarchy in Savings Banner', () => {
    it('displays "The train would save you..." in the savings banner for a multimodal journey with dominant train leg', () => {
      const multimodalArbitrage = {
        ...arbitrage,
        verdict: {
          state: 'transit_cheaper' as const,
          headline: 'The bus would save you about $25 a week', // Legacy default headline
          support: "That's roughly $1,175 a year, and the bus takes 15 minutes longer each day.",
          band: 5,
          differenceWeekly: 25.0,
          savingsWeekly: 25.0,
          savingsAnnual: 1175,
          isWash: false,
          isTransitCheaper: true,
          isDrivingCheaper: false,
          timeDeltaMinutesDaily: 15,
        },
        journeyLegs: [
          {
            id: 'first-mile',
            title: 'Walk to Station',
            type: 'FIRST_MILE' as const,
            mode: 'WALK' as const,
            originName: 'Home',
            destinationName: 'Henderson',
            distanceKm: 0.5,
            durationMins: 5,
            cost: 0,
            costFormatted: 'Free',
            iconName: 'Footprints',
          },
          {
            id: 'transit',
            title: 'Transit Journey',
            type: 'TRANSIT' as const,
            mode: 'BUS' as const,
            originName: 'Henderson',
            destinationName: 'Britomart',
            distanceKm: 20,
            durationMins: 76,
            cost: 4.80,
            costFormatted: '$4.80',
            iconName: 'Bus',
            transitSteps: [
              {
                line: 'Feeder Bus',
                vehicleType: 'BUS',
                durationMins: 3,
              },
              {
                line: 'Western Line',
                vehicleType: 'TRAIN',
                durationMins: 73,
              },
            ],
          },
        ],
      };

      const html = renderToStaticMarkup(
        React.createElement(SummaryTab, {
          commuteInput: {
            ...fixtureInput,
            transitSteps: [
              { line: 'Feeder Bus', vehicleType: 'BUS', durationMins: 3 },
              { line: 'Western Line', vehicleType: 'TRAIN', durationMins: 73 },
            ],
          },
          setCommuteInput: () => {},
          arbitrage: multimodalArbitrage as any,
        })
      );

      assert.ok(
        html.includes('The train would save you about $25 a week'),
        `Summary banner must display "The train would save you...", got: ${html}`
      );
      assert.ok(
        html.includes('By train,'),
        `Public transit time card must display "By train,", got: ${html}`
      );
    });
  });
});
