import { Suburb } from '@/types';

export const AUCKLAND_SUBURBS: Suburb[] = [
  // ZONE 1: Auckland City / Isthmus
  {
    id: 'cbd',
    name: 'Auckland CBD',
    zone: 1,
    region: 'Central',
    coordinates: [174.7645, -36.8485],
    drivingDistanceToCbdKm: 0,
    drivingTimePeakMins: 5,
    drivingTimeOffPeakMins: 5,
    primaryTransitMode: 'Bus',
    transitTimeToCbdMins: 5,
    transitRouteNotes: 'CityLink, InnerLink, Britomart Transport Centre hub',
  },
  {
    id: 'newmarket',
    name: 'Newmarket',
    zone: 1,
    region: 'Central',
    coordinates: [174.7770, -36.8687],
    drivingDistanceToCbdKm: 4.2,
    drivingTimePeakMins: 22,
    drivingTimeOffPeakMins: 10,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 10,
    transitRouteNotes: 'Southern/Western/Onehunga lines direct to Britomart',
  },
  {
    id: 'ponsonby',
    name: 'Ponsonby',
    zone: 1,
    region: 'Central',
    coordinates: [174.7438, -36.8540],
    drivingDistanceToCbdKm: 2.5,
    drivingTimePeakMins: 18,
    drivingTimeOffPeakMins: 8,
    primaryTransitMode: 'Bus',
    transitTimeToCbdMins: 12,
    transitRouteNotes: 'InnerLink & frequent route 82/86 direct into Queen St',
  },
  {
    id: 'grey-lynn',
    name: 'Grey Lynn',
    zone: 1,
    region: 'Central',
    coordinates: [174.7335, -36.8601],
    drivingDistanceToCbdKm: 3.8,
    drivingTimePeakMins: 24,
    drivingTimeOffPeakMins: 12,
    primaryTransitMode: 'Bus',
    transitTimeToCbdMins: 16,
    transitRouteNotes: 'OuterLink & Richmond Rd bus corridor',
  },
  {
    id: 'mt-eden',
    name: 'Mount Eden',
    zone: 1,
    region: 'Central',
    coordinates: [174.7523, -36.8790],
    drivingDistanceToCbdKm: 4.8,
    drivingTimePeakMins: 28,
    drivingTimeOffPeakMins: 14,
    primaryTransitMode: 'Bus',
    transitTimeToCbdMins: 18,
    transitRouteNotes: 'Frequent 27W/27H Mt Eden Rd corridor & future CRL Maungawhau',
  },
  {
    id: 'parnell',
    name: 'Parnell',
    zone: 1,
    region: 'Central',
    coordinates: [174.7797, -36.8550],
    drivingDistanceToCbdKm: 2.1,
    drivingTimePeakMins: 15,
    drivingTimeOffPeakMins: 6,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 7,
    transitRouteNotes: 'Parnell Train Station & InnerLink along Parnell Rd',
  },
  {
    id: 'grafton',
    name: 'Grafton',
    zone: 1,
    region: 'Central',
    coordinates: [174.7647, -36.8617],
    drivingDistanceToCbdKm: 2.3,
    drivingTimePeakMins: 16,
    drivingTimeOffPeakMins: 8,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 8,
    transitRouteNotes: 'Grafton Train Station & Park Rd hospital bus corridor',
  },
  {
    id: 'kingsland',
    name: 'Kingsland',
    zone: 1,
    region: 'Central',
    coordinates: [174.7431, -36.8715],
    drivingDistanceToCbdKm: 4.6,
    drivingTimePeakMins: 25,
    drivingTimeOffPeakMins: 12,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 12,
    transitRouteNotes: 'Western Train Line direct to Britomart',
  },
  {
    id: 'mt-albert',
    name: 'Mount Albert',
    zone: 1,
    region: 'Central',
    coordinates: [174.7188, -36.8837],
    drivingDistanceToCbdKm: 7.2,
    drivingTimePeakMins: 35,
    drivingTimeOffPeakMins: 18,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 18,
    transitRouteNotes: 'Western Train Line & New North Rd frequent bus',
  },
  {
    id: 'greenlane',
    name: 'Greenlane',
    zone: 1,
    region: 'Central',
    coordinates: [174.7938, -36.8920],
    drivingDistanceToCbdKm: 6.8,
    drivingTimePeakMins: 32,
    drivingTimeOffPeakMins: 15,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 14,
    transitRouteNotes: 'Southern Line Greenlane Station & Great South Rd bus',
  },
  {
    id: 'remuera',
    name: 'Remuera',
    zone: 1,
    region: 'Central',
    coordinates: [174.8051, -36.8795],
    drivingDistanceToCbdKm: 6.1,
    drivingTimePeakMins: 30,
    drivingTimeOffPeakMins: 15,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 13,
    transitRouteNotes: 'Remuera Train Station & 75 frequent bus corridor',
  },
  {
    id: 'orakei',
    name: 'Orakei',
    zone: 1,
    region: 'Central',
    coordinates: [174.8143, -36.8622],
    drivingDistanceToCbdKm: 5.4,
    drivingTimePeakMins: 25,
    drivingTimeOffPeakMins: 12,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 8,
    transitRouteNotes: 'Eastern Train Line (1 stop to Britomart) & Tamaki Link',
  },
  {
    id: 'mission-bay',
    name: 'Mission Bay',
    zone: 1,
    region: 'Central',
    coordinates: [174.8329, -36.8587],
    drivingDistanceToCbdKm: 7.8,
    drivingTimePeakMins: 32,
    drivingTimeOffPeakMins: 16,
    primaryTransitMode: 'Bus',
    transitTimeToCbdMins: 22,
    transitRouteNotes: 'Tamaki Link along scenic Tamaki Drive direct to Britomart',
  },
  {
    id: 'pt-chevalier',
    name: 'Point Chevalier',
    zone: 1,
    region: 'Central',
    coordinates: [174.7088, -36.8637],
    drivingDistanceToCbdKm: 6.5,
    drivingTimePeakMins: 30,
    drivingTimeOffPeakMins: 14,
    primaryTransitMode: 'Bus',
    transitTimeToCbdMins: 22,
    transitRouteNotes: 'Frequent bus 66 & OuterLink on Pt Chevalier Rd',
  },
  {
    id: 'epsom',
    name: 'Epsom',
    zone: 1,
    region: 'Central',
    coordinates: [174.7672, -36.8860],
    drivingDistanceToCbdKm: 5.2,
    drivingTimePeakMins: 26,
    drivingTimeOffPeakMins: 14,
    primaryTransitMode: 'Bus',
    transitTimeToCbdMins: 19,
    transitRouteNotes: 'Manukau Rd frequent bus corridor direct to Civic',
  },

  // ZONE 2: Inner North Shore, Inner West, Inner South, Inner East
  {
    id: 'takapuna',
    name: 'Takapuna',
    zone: 2,
    region: 'North Shore',
    coordinates: [174.7733, -36.7876],
    drivingDistanceToCbdKm: 9.1,
    drivingTimePeakMins: 35,
    drivingTimeOffPeakMins: 15,
    primaryTransitMode: 'Northern Busway',
    transitTimeToCbdMins: 18,
    transitRouteNotes: 'Akoranga Busway Station (NX1/NX2) & route 82',
  },
  {
    id: 'devonport',
    name: 'Devonport',
    zone: 2,
    region: 'North Shore',
    coordinates: [174.7960, -36.8315],
    drivingDistanceToCbdKm: 15.2,
    drivingTimePeakMins: 45,
    drivingTimeOffPeakMins: 22,
    primaryTransitMode: 'Ferry',
    transitTimeToCbdMins: 12,
    transitRouteNotes: 'Devonport Ferry direct to Downtown Ferry Terminal (under $50 cap!)',
  },
  {
    id: 'northcote',
    name: 'Northcote',
    zone: 2,
    region: 'North Shore',
    coordinates: [174.7478, -36.8042],
    drivingDistanceToCbdKm: 7.5,
    drivingTimePeakMins: 30,
    drivingTimeOffPeakMins: 12,
    primaryTransitMode: 'Northern Busway',
    transitTimeToCbdMins: 15,
    transitRouteNotes: 'Smales Farm / Akoranga Busway & 923 via Onewa Rd',
  },
  {
    id: 'birkenhead',
    name: 'Birkenhead',
    zone: 2,
    region: 'North Shore',
    coordinates: [174.7262, -36.8166],
    drivingDistanceToCbdKm: 9.6,
    drivingTimePeakMins: 38,
    drivingTimeOffPeakMins: 16,
    primaryTransitMode: 'Ferry',
    transitTimeToCbdMins: 14,
    transitRouteNotes: 'Birkenhead Wharf Ferry or Onewa T3 transit lane bus',
  },
  {
    id: 'mt-roskill',
    name: 'Mount Roskill',
    zone: 2,
    region: 'Central',
    coordinates: [174.7305, -36.9080],
    drivingDistanceToCbdKm: 9.3,
    drivingTimePeakMins: 38,
    drivingTimeOffPeakMins: 18,
    primaryTransitMode: 'Bus',
    transitTimeToCbdMins: 28,
    transitRouteNotes: 'Dominion Rd 25B/25L bus rapid corridor',
  },
  {
    id: 'onehunga',
    name: 'Onehunga',
    zone: 2,
    region: 'Central',
    coordinates: [174.7865, -36.9242],
    drivingDistanceToCbdKm: 10.4,
    drivingTimePeakMins: 40,
    drivingTimeOffPeakMins: 20,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 24,
    transitRouteNotes: 'Onehunga Line Train direct to Newmarket & Britomart',
  },
  {
    id: 'ellerslie',
    name: 'Ellerslie',
    zone: 2,
    region: 'Central',
    coordinates: [174.8080, -36.8994],
    drivingDistanceToCbdKm: 8.6,
    drivingTimePeakMins: 34,
    drivingTimeOffPeakMins: 16,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 17,
    transitRouteNotes: 'Southern Line Ellerslie Train Station',
  },
  {
    id: 'penrose',
    name: 'Penrose',
    zone: 2,
    region: 'Central',
    coordinates: [174.8197, -36.9135],
    drivingDistanceToCbdKm: 10.1,
    drivingTimePeakMins: 38,
    drivingTimeOffPeakMins: 18,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 19,
    transitRouteNotes: 'Penrose junction station (Southern & Onehunga lines)',
  },
  {
    id: 'new-lynn',
    name: 'New Lynn',
    zone: 2,
    region: 'West',
    coordinates: [174.6860, -36.9086],
    drivingDistanceToCbdKm: 12.3,
    drivingTimePeakMins: 45,
    drivingTimeOffPeakMins: 22,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 25,
    transitRouteNotes: 'New Lynn Transport Interchange & Western Train line',
  },
  {
    id: 'avondale',
    name: 'Avondale',
    zone: 2,
    region: 'West',
    coordinates: [174.6975, -36.8970],
    drivingDistanceToCbdKm: 10.2,
    drivingTimePeakMins: 40,
    drivingTimeOffPeakMins: 20,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 21,
    transitRouteNotes: 'Avondale Station Western Line & Rosebank Rd bus',
  },
  {
    id: 'st-heliers',
    name: 'St Heliers',
    zone: 2,
    region: 'East',
    coordinates: [174.8550, -36.8580],
    drivingDistanceToCbdKm: 10.8,
    drivingTimePeakMins: 42,
    drivingTimeOffPeakMins: 22,
    primaryTransitMode: 'Bus',
    transitTimeToCbdMins: 32,
    transitRouteNotes: 'Tamaki Link coastal route via Kohimarama and Mission Bay',
  },

  // ZONE 3: Mid-ring (Henderson, Sylvia Park, Howick, Glenfield, Panmure)
  {
    id: 'glenfield',
    name: 'Glenfield',
    zone: 3,
    region: 'North Shore',
    coordinates: [174.7175, -36.7842],
    drivingDistanceToCbdKm: 13.5,
    drivingTimePeakMins: 46,
    drivingTimeOffPeakMins: 22,
    primaryTransitMode: 'Bus',
    transitTimeToCbdMins: 32,
    transitRouteNotes: 'Frequent bus 917 to Smales Farm Busway / 95B to City',
  },
  {
    id: 'milford',
    name: 'Milford',
    zone: 3,
    region: 'North Shore',
    coordinates: [174.7660, -36.7690],
    drivingDistanceToCbdKm: 12.8,
    drivingTimePeakMins: 42,
    drivingTimeOffPeakMins: 20,
    primaryTransitMode: 'Northern Busway',
    transitTimeToCbdMins: 26,
    transitRouteNotes: 'Feeder bus to Smales Farm Station then NX1 to CBD',
  },
  {
    id: 'henderson',
    name: 'Henderson',
    zone: 3,
    region: 'West',
    coordinates: [174.6320, -36.8810],
    drivingDistanceToCbdKm: 16.8,
    drivingTimePeakMins: 55,
    drivingTimeOffPeakMins: 25,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 38,
    transitRouteNotes: 'Henderson Rail Interchange (Western Line direct to Britomart)',
  },
  {
    id: 'te-atatu',
    name: 'Te Atatu Peninsula',
    zone: 3,
    region: 'West',
    coordinates: [174.6540, -36.8400],
    drivingDistanceToCbdKm: 14.5,
    drivingTimePeakMins: 48,
    drivingTimeOffPeakMins: 20,
    primaryTransitMode: 'Bus',
    transitTimeToCbdMins: 30,
    transitRouteNotes: 'Route 132/133 via SH16 Northwestern Busway priority',
  },
  {
    id: 'sylvia-park',
    name: 'Sylvia Park (Mt Wellington)',
    zone: 3,
    region: 'Central',
    coordinates: [174.8420, -36.9150],
    drivingDistanceToCbdKm: 12.9,
    drivingTimePeakMins: 46,
    drivingTimeOffPeakMins: 20,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 20,
    transitRouteNotes: 'Sylvia Park Train Station (Eastern Line direct to Britomart)',
  },
  {
    id: 'panmure',
    name: 'Panmure',
    zone: 3,
    region: 'East',
    coordinates: [174.8505, -36.8980],
    drivingDistanceToCbdKm: 12.1,
    drivingTimePeakMins: 44,
    drivingTimeOffPeakMins: 22,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 18,
    transitRouteNotes: 'Panmure Rail/AMETI Busway Interchange (Eastern Line)',
  },
  {
    id: 'otahuhu',
    name: 'Otahuhu',
    zone: 3,
    region: 'South',
    coordinates: [174.8425, -36.9440],
    drivingDistanceToCbdKm: 15.6,
    drivingTimePeakMins: 52,
    drivingTimeOffPeakMins: 24,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 22,
    transitRouteNotes: 'Otahuhu Station Southern & Eastern line dual-connectivity',
  },
  {
    id: 'pakuranga',
    name: 'Pakuranga',
    zone: 3,
    region: 'East',
    coordinates: [174.8870, -36.9030],
    drivingDistanceToCbdKm: 15.2,
    drivingTimePeakMins: 54,
    drivingTimeOffPeakMins: 24,
    primaryTransitMode: 'Bus',
    transitTimeToCbdMins: 30,
    transitRouteNotes: 'Eastern Busway priority route 70 via Panmure rail connection',
  },
  {
    id: 'howick',
    name: 'Howick',
    zone: 3,
    region: 'East',
    coordinates: [174.9310, -36.8960],
    drivingDistanceToCbdKm: 21.0,
    drivingTimePeakMins: 62,
    drivingTimeOffPeakMins: 32,
    primaryTransitMode: 'Bus',
    transitTimeToCbdMins: 45,
    transitRouteNotes: 'Route 70 / 72X express or Half Moon Bay ferry connection',
  },
  {
    id: 'glen-eden',
    name: 'Glen Eden',
    zone: 3,
    region: 'West',
    coordinates: [174.6540, -36.9090],
    drivingDistanceToCbdKm: 15.8,
    drivingTimePeakMins: 52,
    drivingTimeOffPeakMins: 26,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 32,
    transitRouteNotes: 'Glen Eden Train Station Western Line',
  },

  // ZONE 4: Outer Ring (Albany, Westgate, Manukau, Botany, Papatoetoe)
  {
    id: 'albany',
    name: 'Albany',
    zone: 4,
    region: 'North Shore',
    coordinates: [174.7040, -36.7320],
    drivingDistanceToCbdKm: 19.5,
    drivingTimePeakMins: 58,
    drivingTimeOffPeakMins: 24,
    primaryTransitMode: 'Northern Busway',
    transitTimeToCbdMins: 28,
    transitRouteNotes: 'Albany Busway Station (NX1 rapid dedicated busway direct to CBD)',
  },
  {
    id: 'browns-bay',
    name: 'Browns Bay',
    zone: 4,
    region: 'North Shore',
    coordinates: [174.7470, -36.7160],
    drivingDistanceToCbdKm: 21.5,
    drivingTimePeakMins: 60,
    drivingTimeOffPeakMins: 26,
    primaryTransitMode: 'Northern Busway',
    transitTimeToCbdMins: 38,
    transitRouteNotes: 'Route 83/856 to Albany Busway Station + NX1 to CBD',
  },
  {
    id: 'westgate',
    name: 'Westgate (Massey)',
    zone: 4,
    region: 'West',
    coordinates: [174.6150, -36.8180],
    drivingDistanceToCbdKm: 18.5,
    drivingTimePeakMins: 56,
    drivingTimeOffPeakMins: 22,
    primaryTransitMode: 'Bus',
    transitTimeToCbdMins: 34,
    transitRouteNotes: 'WX1 Western Express via Northwestern motorway busway',
  },
  {
    id: 'massey',
    name: 'Massey East',
    zone: 4,
    region: 'West',
    coordinates: [174.6290, -36.8370],
    drivingDistanceToCbdKm: 17.2,
    drivingTimePeakMins: 52,
    drivingTimeOffPeakMins: 22,
    primaryTransitMode: 'Bus',
    transitTimeToCbdMins: 36,
    transitRouteNotes: 'WX1 / route 11 bus into CBD',
  },
  {
    id: 'mangere',
    name: 'Mangere',
    zone: 4,
    region: 'South',
    coordinates: [174.7980, -36.9650],
    drivingDistanceToCbdKm: 17.8,
    drivingTimePeakMins: 55,
    drivingTimeOffPeakMins: 24,
    primaryTransitMode: 'Bus',
    transitTimeToCbdMins: 42,
    transitRouteNotes: 'Airport Link 38 bus to Onehunga/Puhinui rail interchange',
  },
  {
    id: 'manukau',
    name: 'Manukau Central',
    zone: 4,
    region: 'South',
    coordinates: [174.8810, -36.9920],
    drivingDistanceToCbdKm: 23.4,
    drivingTimePeakMins: 65,
    drivingTimeOffPeakMins: 28,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 38,
    transitRouteNotes: 'Manukau Rail Interchange (Eastern Line direct to Britomart)',
  },
  {
    id: 'botany-downs',
    name: 'Botany Downs',
    zone: 4,
    region: 'East',
    coordinates: [174.9120, -36.9320],
    drivingDistanceToCbdKm: 21.8,
    drivingTimePeakMins: 65,
    drivingTimeOffPeakMins: 30,
    primaryTransitMode: 'Bus',
    transitTimeToCbdMins: 45,
    transitRouteNotes: 'Route 70 frequent bus via Panmure rail connection',
  },
  {
    id: 'papatoetoe',
    name: 'Papatoetoe',
    zone: 4,
    region: 'South',
    coordinates: [174.8560, -36.9740],
    drivingDistanceToCbdKm: 20.2,
    drivingTimePeakMins: 60,
    drivingTimeOffPeakMins: 26,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 32,
    transitRouteNotes: 'Papatoetoe Train Station (Southern Line express service)',
  },
  {
    id: 'hobsonville',
    name: 'Hobsonville Point',
    zone: 4,
    region: 'West',
    coordinates: [174.6590, -36.7920],
    drivingDistanceToCbdKm: 21.0,
    drivingTimePeakMins: 62,
    drivingTimeOffPeakMins: 25,
    primaryTransitMode: 'Ferry',
    transitTimeToCbdMins: 35,
    transitRouteNotes: 'Hobsonville Point Ferry to Downtown Ferry Terminal (under $50 cap!)',
  },
  {
    id: 'half-moon-bay',
    name: 'Half Moon Bay',
    zone: 4,
    region: 'East',
    coordinates: [174.9030, -36.8770],
    drivingDistanceToCbdKm: 19.8,
    drivingTimePeakMins: 58,
    drivingTimeOffPeakMins: 28,
    primaryTransitMode: 'Ferry',
    transitTimeToCbdMins: 40,
    transitRouteNotes: 'Half Moon Bay Ferry directly to CBD Downtown terminal',
  },

  // ZONE 5: Fringe / Outer Metro (Silverdale, Orewa, Papakura, Pukekohe, Drury)
  {
    id: 'silverdale',
    name: 'Silverdale',
    zone: 5,
    region: 'Fringe',
    coordinates: [174.6720, -36.6210],
    drivingDistanceToCbdKm: 32.5,
    drivingTimePeakMins: 75,
    drivingTimeOffPeakMins: 34,
    primaryTransitMode: 'Northern Busway',
    transitTimeToCbdMins: 45,
    transitRouteNotes: 'Hibiscus Coast Busway Station (NX1 express direct to Britomart)',
  },
  {
    id: 'orewa',
    name: 'Orewa',
    zone: 5,
    region: 'Fringe',
    coordinates: [174.6940, -36.5860],
    drivingDistanceToCbdKm: 38.0,
    drivingTimePeakMins: 85,
    drivingTimeOffPeakMins: 40,
    primaryTransitMode: 'Northern Busway',
    transitTimeToCbdMins: 55,
    transitRouteNotes: 'Route 981 connecting to Hibiscus Coast Busway NX1',
  },
  {
    id: 'whangaparaoa',
    name: 'Whangaparaoa',
    zone: 5,
    region: 'Fringe',
    coordinates: [174.7610, -36.6340],
    drivingDistanceToCbdKm: 42.0,
    drivingTimePeakMins: 90,
    drivingTimeOffPeakMins: 45,
    primaryTransitMode: 'Bus',
    transitTimeToCbdMins: 65,
    transitRouteNotes: 'Route 982/983 to Hibiscus Coast busway interchange',
  },
  {
    id: 'kumeu',
    name: 'Kumeu / Huapai',
    zone: 5,
    region: 'Fringe',
    coordinates: [174.5570, -36.7750],
    drivingDistanceToCbdKm: 28.5,
    drivingTimePeakMins: 72,
    drivingTimeOffPeakMins: 32,
    primaryTransitMode: 'Bus',
    transitTimeToCbdMins: 55,
    transitRouteNotes: 'Route 126/129 connecting to WX1 Western Express at Westgate',
  },
  {
    id: 'papakura',
    name: 'Papakura',
    zone: 5,
    region: 'South',
    coordinates: [174.9450, -37.0650],
    drivingDistanceToCbdKm: 32.0,
    drivingTimePeakMins: 80,
    drivingTimeOffPeakMins: 35,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 50,
    transitRouteNotes: 'Papakura Rail Terminus (Southern Line direct to Britomart)',
  },
  {
    id: 'drury',
    name: 'Drury',
    zone: 5,
    region: 'South',
    coordinates: [174.9530, -37.1030],
    drivingDistanceToCbdKm: 36.5,
    drivingTimePeakMins: 85,
    drivingTimeOffPeakMins: 38,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 58,
    transitRouteNotes: 'Feeder bus to Papakura Station Southern Line',
  },
  {
    id: 'takanini',
    name: 'Takanini',
    zone: 5,
    region: 'South',
    coordinates: [174.9220, -37.0370],
    drivingDistanceToCbdKm: 28.2,
    drivingTimePeakMins: 72,
    drivingTimeOffPeakMins: 32,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 44,
    transitRouteNotes: 'Takanini Train Station (Southern Line)',
  },
  {
    id: 'pukekohe',
    name: 'Pukekohe',
    zone: 5,
    region: 'Fringe',
    coordinates: [174.9080, -37.2010],
    drivingDistanceToCbdKm: 51.0,
    drivingTimePeakMins: 95,
    drivingTimeOffPeakMins: 50,
    primaryTransitMode: 'Train',
    transitTimeToCbdMins: 68,
    transitRouteNotes: 'Pukekohe Rail electric shuttle connecting to Southern Line at Papakura',
  },
];

export function getSuburbById(id: string): Suburb {
  const found = AUCKLAND_SUBURBS.find((s) => s.id === id);
  if (!found) {
    // Default to Albany or CBD if invalid
    return AUCKLAND_SUBURBS[0];
  }
  return found;
}

// Great circle distance in km
export function haversineDistanceKm(
  [lon1, lat1]: [number, number],
  [lon2, lat2]: [number, number]
): number {
  const R = 6371; // Earth radius in km
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}

export function estimateRouteMetrics(
  origin: Suburb,
  destination: Suburb
): {
  distanceKm: number;
  drivingTimePeakMins: number;
  transitTimeMins: number;
  zonesTraveled: number;
} {
  if (origin.id === destination.id) {
    return {
      distanceKm: 2.0,
      drivingTimePeakMins: 8,
      transitTimeMins: 10,
      zonesTraveled: 1,
    };
  }

  // If destination is CBD, use precalculated values
  if (destination.id === 'cbd') {
    return {
      distanceKm: origin.drivingDistanceToCbdKm,
      drivingTimePeakMins: origin.drivingTimePeakMins,
      transitTimeMins: origin.transitTimeToCbdMins,
      zonesTraveled: origin.zone,
    };
  }

  // If origin is CBD, use destination values
  if (origin.id === 'cbd') {
    return {
      distanceKm: destination.drivingDistanceToCbdKm,
      drivingTimePeakMins: destination.drivingTimePeakMins,
      transitTimeMins: destination.transitTimeToCbdMins,
      zonesTraveled: destination.zone,
    };
  }

  // Suburb to Suburb
  const straightLine = haversineDistanceKm(origin.coordinates, destination.coordinates);
  // Road network winding multiplier in Auckland (bridges, harbour, motorways)
  const windingMultiplier = 1.34;
  const distanceKm = Math.round(straightLine * windingMultiplier * 10) / 10;

  // Zone calculation: AT HOP calculates zones crossed based on zone boundaries
  const zonesTraveled = Math.min(5, Math.max(1, Math.abs(origin.zone - destination.zone) + 1));

  // Time estimates
  const drivingTimePeakMins = Math.round(distanceKm * 2.1 + 8);
  const transitTimeMins = Math.round(
    Math.min(origin.transitTimeToCbdMins + destination.transitTimeToCbdMins * 0.7, distanceKm * 2.3 + 15)
  );

  return {
    distanceKm,
    drivingTimePeakMins,
    transitTimeMins,
    zonesTraveled,
  };
}
