'use client';

import React from 'react';
import { CommuteVerdict } from '@/types/commute';
import { Sparkles, Scale, Car } from 'lucide-react';

export interface VerdictCardProps {
  verdict?: CommuteVerdict;
  className?: string;
}

const DEFAULT_VERDICT: CommuteVerdict = {
  state: 'about_the_same',
  headline: 'Pretty much a wash',
  support: 'Compare driving and public transport costs to see your personal financial verdict.',
  band: 3,
  differenceWeekly: 0,
  savingsWeekly: 0,
  savingsAnnual: 0,
  timeDeltaMinutesDaily: 0,
  isWash: true,
  isTransitCheaper: false,
  isDrivingCheaper: false,
};

/**
 * VerdictCard (STORY-4)
 * Displays the plain-language financial verdict headline and supporting sentence
 * generated by the pure calculateVerdict engine (STORY-2).
 */
export default function VerdictCard({ verdict, className = '' }: VerdictCardProps) {
  const activeVerdict = verdict || DEFAULT_VERDICT;
  const isTransitCheaper = activeVerdict.state === 'transit_cheaper';
  const isWash = activeVerdict.state === 'about_the_same';

  const badgeConfig = isTransitCheaper
    ? {
        label: 'Transit Saves Money',
        icon: Sparkles,
        badgeClass: 'bg-emerald-500/15 text-emerald-300 border-emerald-500/30',
        cardBorder: 'border-emerald-500/20',
      }
    : isWash
    ? {
        label: 'Cost Wash',
        icon: Scale,
        badgeClass: 'bg-sky-500/15 text-sky-300 border-sky-500/30',
        cardBorder: 'border-sky-500/20',
      }
    : {
        label: 'Driving Is Cheaper',
        icon: Car,
        badgeClass: 'bg-amber-500/15 text-amber-300 border-amber-500/30',
        cardBorder: 'border-amber-500/20',
      };

  const BadgeIcon = badgeConfig.icon;

  return (
    <div
      aria-label="Commute verdict summary"
      className={`relative overflow-hidden rounded-2xl border ${badgeConfig.cardBorder} bg-slate-900/90 p-6 sm:p-8 backdrop-blur-md shadow-xl shadow-black/40 transition-all ${className}`}
    >
      {/* Subtle background glow */}
      <div
        className={`absolute -right-16 -top-16 w-56 h-56 rounded-full blur-3xl pointer-events-none opacity-20 ${
          isTransitCheaper ? 'bg-emerald-500' : isWash ? 'bg-sky-500' : 'bg-amber-500'
        }`}
      />

      <div className="relative z-10 flex flex-col items-start gap-3">
        <div
          className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold tracking-wide uppercase border ${badgeConfig.badgeClass}`}
        >
          <BadgeIcon className="w-3.5 h-3.5" aria-hidden="true" />
          <span>{badgeConfig.label}</span>
        </div>

        <h2 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight leading-snug">
          {activeVerdict.headline}
        </h2>

        <p className="text-base sm:text-lg text-slate-300 font-normal leading-relaxed max-w-2xl">
          {activeVerdict.support}
        </p>
      </div>
    </div>
  );
}
